### ISSUE TITLE
Adding a configuration file to use Yarn workspace

### ISSUE THREAD

**Issue by GHEMID-Mohamed** [julien-f/react-todos#1]
Yarn install doesn't work unless you add a file named : **.yarnrc** and add this line to it : **workspaces-experimental true**

**Comment by julien-f** [comment]
It should not be necessary, which version of Yarn are you using?

**Comment by GHEMID-Mohamed** [comment]
v0.27.5

**Comment by julien-f** [comment]
You need to update: https://github.com/yarnpkg/yarn/releases
